server:
  port: 80
freemarker:

  allow-request-override: false

  cache: false

  check-template-location: true

  charset: UTF-8

  content-type: text/html; charset=utf-8

  expose-request-attributes: false

  expose-session-attributes: false

  expose-spring-macro-helpers: false

  ## 模版文件结尾.ftl

  suffix: .ftl

  ## 模版文件目录

  template-loader-path: classpath:/templates
self:
  ciphertext: ACC0515F34056AD8E32238910C6C3100